### ISSUE TITLE
RPC - Everything show as "unknown"

### ISSUE THREAD

**Issue by Scarlaid** [xAkre/Wuthering-Waves-RPC#1]
I have tried both
- Run the game first then the RPC
- Run the RPC then the game
I have also tried to teleport to different location right when I logged in, no luck
Am I missing something or this is a first release issue
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/90851437/d4f21392-d0e3-48e9-ae5c-41d9176b65ed)

**Comment by xAkre** [comment]
Would you mind launching the RPC one more time and pasting the contents of the log file that should be located at C:/Users/Your Username/AppData/Local/WutheringWavesRPC

**Comment by Scarlaid** [comment]
[log.txt](https://github.com/xAkre/Wuthering-Waves-RPC/files/15452916/log.txt)
sorry for the late response, here you go

**Comment by xAkre** [comment]
The problem seems to be in the fact that the RPC cannot get a connection to the WuWa local database. Did you maybe change the install location of the Wuthering Waves folder when installing it? The RPC assumes the location to be

```
C:/Wuthering Waves
```

and this is hard coded for now.

If it is installed there could you check if 
```
C:/Wuthering Waves/Wuthering Waves Game/Client/Saved/LocalStorage/LocalStorage.db
```
exists?

**Comment by Scarlaid** [comment]
My game is installed on the E:/ drive, which is this 

> E:\Games\Wuthering Waves\Wuthering Waves Game\Client\Saved\LocalStorage\LocalStorage.db

**Comment by xAkre** [comment]
I'm currently working on a way to change the install location without having to build from source. However, for now the only way you could get the RPC to work is:
- Install [Python](https://www.python.org/downloads/)
- Clone the repository
- Run `pip install -r requirements.txt`
- Change the following line inside of [config.py](https://github.com/xAkre/Wuthering-Waves-RPC/blob/master/config.py):
```python
LOCAL_DATABASE_PATH = "C:\\Wuthering Waves\\Wuthering Waves Game\\Client\\Saved\\LocalStorage\\LocalStorage.db"
```
to:
```python
LOCAL_DATABASE_PATH = "E:\\Games\\Wuthering Waves\\Wuthering Waves Game\\Client\\Saved\\LocalStorage\\LocalStorage.db"
```
- Run `pyinstaller wuthering_waves_rpc.spec`
- The executable should be located in the dist folder

**Comment by Scarlaid** [comment]
This one worked well, thanks for the guide :D
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/90851437/d441f0e3-1443-49e8-a36a-efd8de4e4d46)

Should I close this?

**Comment by xAkre** [comment]
Leave it open for now in case anyone encounters the same issue. I will close it once i add a way to customize the install path

**Comment by xAkre** [comment]
As of [v1.1.0](https://github.com/xAkre/Wuthering-Waves-RPC/releases/tag/v1.1.0), you can now set the Wuthering Waves install path when installing
