### ISSUE TITLE
Does not show anything 

### ISSUE THREAD

**Issue by CCrriimm** [xAkre/Wuthering-Waves-RPC#12]
does not work just says waiting 
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/169927259/aa3aa660-9f9d-43f5-b21c-a8a440031d55)
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/169927259/192b6e49-d90a-4de3-8cd3-ab9764869a7b)

**Comment by xAkre** [comment]
Could you have a look at https://github.com/xAkre/Wuthering-Waves-RPC/issues/9 and see if the situation is the same

**Comment by CCrriimm** [comment]
yes it is the same  but i cant follow what you said for the fix

**Comment by CCrriimm** [comment]
nvm i already understand 
already fixed

**Comment by CCrriimm** [comment]
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/169927259/075e03b7-fbee-453b-8e49-1026edce60b4)
