### ISSUE TITLE
im getting this error please help

### ISSUE THREAD

**Issue by kurumifps** [xAkre/Wuthering-Waves-RPC#15]
![issue](https://github.com/xAkre/Wuthering-Waves-RPC/assets/160056320/9d6336e1-90fd-46e8-a4f1-aba5a884fc89)

**Comment by xAkre** [comment]
There is some sort of error when creating a Desktop shortcut, and I can't really help much with that. You can create the shortcut yourself if you want it. The error won't affect the program in any way
