### ISSUE TITLE
uninstall ?

### ISSUE THREAD

**Issue by spix18** [xAkre/Wuthering-Waves-RPC#3]
title, how to uninstall this ?

**Comment by lingzn12** [comment]
> 标题，如何卸载这个？

direct uninstall，I'm like this.

**Comment by xAkre** [comment]
I am working on a direct executable for this. Currently you have to remove the folder and related items

**Comment by xAkre** [comment]
As of [v1.1.2](https://github.com/xAkre/Wuthering-Waves-RPC/releases/tag/v1.1.2), the RPC comes with an uninstaller
