### ISSUE TITLE
program exits when game exits

### ISSUE THREAD

**Issue by minbcrafter** [xAkre/Wuthering-Waves-RPC#5]
don't know if this is intended behavior, but if i want to play the game again and have rich presence, i have to manually reopen the rpc.
would be cool if the rpc stayed open waiting for wuwa to be run after wuwa closes

**Comment by xAkre** [comment]
It's indeed intended behavior so that the process isn't running when it doesn't need to be, as some people don't like that. I can add an option during setup for this, however, and it shouldn't be hard to implement

**Comment by Kartonowy** [comment]
Just when its on idle maybe change the refresh rate for checking so it is not waiting *just* 15 miliseconds. Like maybe once every few or more seconds, and if wuwa process is running then resume with standard 15 based sleep-loop. 

It would then reduce the amount of times rpc has to check for process and reduce the usage of cpu as it checks registers less.

edit: idle meaning no wuwa running

**Comment by xAkre** [comment]
Would be a good idea to reduce the refresh rate. It currently updates every 15 seconds, every 15 ms would be quite insane. I think 30 seconds should be alright

**Comment by xAkre** [comment]
The option is available in [v1.1.3](https://github.com/xAkre/Wuthering-Waves-RPC/releases/tag/v1.1.3)
