### ISSUE TITLE
Possible false positive?

### ISSUE THREAD

**Issue by xDuva** [xAkre/Wuthering-Waves-RPC#7]
I've had the .exe file tagged as spy-/malware and quarantined by both Windows Defender and Malwarebytes. Any reason why that might happened? Is it because of the way how it interacts with the LocalDatabase file and then sends the info to discord?

**Comment by xAkre** [comment]
Can't say i know how Windows Defender or Malwarebytes detect a program as malware. If anyone has any idea feel free to chime in

**Comment by Scarlaid** [comment]
Might be unrelated to what Akre mentioned, but you can always throw the file on VirusTotal
- [Installer](https://www.virustotal.com/gui/file/44fd662dff3f61e6a0639561c7ae255dc80dda8e6d7f51139388b5c9d03aec26) 
- [RPC](https://www.virustotal.com/gui/file/c6d9c0528ea95e518b8582b59b6fb8112e226d47180f154e13c36e4b242540e8)

Best I can know is:
> When you create a new executable Defender will not recognize the code in your executable and the executable is not signed so Defender will flag it as a possible virus the best option is to create an exclusion to the new .exe and its folder in Defender to stop it being flagged.

Could help, or not.

**Comment by xAkre** [comment]
I will close this issue, as I don't think much can be done. It's possible the setup executable gets flagged because it accesses the windows task scheduler to make it launch on start-up, but there isn't another reliable method to do this that i am aware of
