### ISSUE TITLE
It's open, but do nothing

### ISSUE THREAD

**Issue by julien973** [xAkre/Wuthering-Waves-RPC#9]
Humm, it dosn't work for me, i mean it's stil open, but do nothing else

**Comment by xAkre** [comment]
Could you launch the RPC, wait a minute or two, and then copy the contents of the log file that should be located at 

```
{The folder you installed the RPC in}/logs/log.txt
```

and paste it here?

**Comment by julien973** [comment]
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/39602332/7aa43cc5-5988-4d1e-8789-7810924c98bb)

[INFO] [2024-06-01 18:45:04.592301] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:45:19.602889] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:45:34.615231] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:45:49.630800] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:46:04.645938] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:46:19.672251] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:46:34.690003] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:46:49.708485] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:47:04.725170] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:47:19.740749] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:47:34.758304] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:47:49.775282] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:48:04.795526] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:48:19.812956] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:48:34.829822] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:48:49.848510] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:49:04.868365] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:49:19.879563] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:49:34.892568] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:49:49.913959] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:50:04.932423] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:50:19.948354] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:50:34.965366] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:50:49.978251] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:51:04.989699] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:51:20.000492] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:51:35.012589] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:51:50.029188] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:52:05.040703] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:52:20.060081] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:52:35.076250] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:52:50.090476] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:53:05.104077] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:53:20.116565] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:53:35.137070] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:53:50.155847] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:54:05.179307] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:54:20.206715] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:54:35.221923] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:54:50.241480] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:55:05.251616] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:55:20.265755] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:55:35.279714] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:55:50.296987] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:56:05.308578] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:56:20.326038] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:56:35.343357] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:56:50.358341] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:57:05.368823] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:57:20.386231] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:57:35.402776] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:57:50.417728] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:58:05.433628] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:58:20.444121] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:58:35.457519] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:58:50.472736] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:59:05.485007] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:59:20.497132] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:59:35.513192] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 18:59:50.527113] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:00:05.540059] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:00:20.551365] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:00:35.560847] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:00:50.570636] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:01:05.580396] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:01:20.593198] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:01:35.608896] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:01:50.621107] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:02:05.633301] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:02:20.644811] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:02:35.655765] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:02:50.669180] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:03:05.678123] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:03:20.692097] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:03:35.704072] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:03:50.732923] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:04:05.742443] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:04:20.758835] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:04:35.778921] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:04:50.798269] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:05:05.818892] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:05:20.835199] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:05:35.852832] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:05:50.866799] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:06:05.877984] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:06:20.890105] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:06:35.907992] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:06:50.921327] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:07:05.933022] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:07:20.947840] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:07:35.965609] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:07:50.980667] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:08:05.991175] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:08:21.006138] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:08:36.018022] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:08:51.031878] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:09:06.043917] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:09:21.066453] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:09:36.087981] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:09:51.101224] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:10:06.116540] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:10:21.130459] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:10:36.143399] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:10:51.157907] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:11:06.171912] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:11:21.185785] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:11:36.200972] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:11:51.249317] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:12:06.261576] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:12:21.275979] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:12:36.290397] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:12:51.301363] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:13:06.320395] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:13:21.334417] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:13:36.350808] Wuthering Waves is not running, waiting...
[INFO] [2024-06-01 19:13:51.370006] Wuthering Waves is not running, waiting...

**Comment by xAkre** [comment]
In Task Manager, is the Wuthering Waves process called "Wuthering Waves" or do you have it in another language?

**Comment by julien973** [comment]
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/39602332/25571e1c-6f4e-408a-b903-1344e824a3bb)

**Comment by xAkre** [comment]
That would probably be the issue. The RPC checks for a process named Wuthering Waves, and I don't really know how else it could identify whether Wuthering Waves is running, nor do I know why the process is called that for you. If you would like to get it working now you can:

1. Clone the repo
2. Download [Python](https://www.python.org/downloads/)
3. Run `pip install -r requirements.txt`
4. Change the following line in [config.py](https://github.com/xAkre/Wuthering-Waves-RPC/blob/master/config.py)
```python
MAIN_EXECUTABLE_NAME = "Wuthering Waves RPC.exe"
```
to
```python
MAIN_EXECUTABLE_NAME = "Client-Win64-Shipping.exe"
```
5. Run `build.bat`
6. Run the setup executable located in the `dist/` directory

I will try to look into a way to identify whether Wuthering Waves is running without relying on the process name

**Comment by julien973** [comment]
Okay :)

**Comment by xAkre** [comment]
My bad don't change

```python
MAIN_EXECUTABLE_NAME = "Wuthering Waves RPC.exe"
```

change

```python
WUWA_PROCESS_NAME = "Wuthering Waves.exe"
```

**Comment by julien973** [comment]
Yes, don't worry, I know a thing or two about it and I noticed the mistake

**Comment by julien973** [comment]
Okay, all things working well
Thanks you very much for your help and assitance  :D
